# Generated by Django 6.1 on 2026-08-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='counter_view',
            field=models.IntegerField(default=0),
        ),
    ]
