# Generated by Django 6.1 on 2026-08-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
