# Generated by Django 6.1 on 2026-08-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
